name: EasyAFK
version: '1.1-SNAPSHOT'
main: top.abmcar.easyafk.EasyAFK
depend: [ Vault, PlaceholderAPI ]
authors: [ abmcar ]
description: Auto AFK
commands:
  EasyAFK:
    aliases:
      - "eafk"
    usage: "/EasyAFK help - show usage."
    description: "Reload config."
    permission: "EasyAFK.reload"
    permission-message: "No Permission!"